version: '3.9'

services:
  db:
    container_name: db
    ports:
    - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=root
    image: postgres:latest
    networks:
      - hospitalNetwork

  hospital:
    container_name: hospital
    image: poviraevsergei/hospital:v3
    ports:
    - "8080:8080"
    environment:
     - DB_HOST=db
    depends_on:
      - db
    networks:
      - hospitalNetwork

networks:
  hospitalNetwork:



